apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.Route.name | default "api-app-route" }}
  namespace: {{ .Values.Route.namespace | default "ameen2607-dev" }}
spec:
  to:
    kind: Service
    name: {{ .Values.service.name | default "api-app-service" }}
  port:
    targetPort: {{ .Values.Route.targetPort | default 5000 }}
  tls:
    termination: {{ .Values.Route.termination | default "edge" }}
