apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default "api-app-service" }}
  namespace: {{ .Values.service.namespace | default "ameen2607-dev" }}
spec:
  selector:
    app: {{ .Values.Deployment.name | default "api-app" }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type | default "ClusterIP" }}
  