apiVersion: v1
kind: Pod
metadata:
  name: "api-app-test-connection"
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["sh", "-c", "curl -sf http://{{ .Values.service.name }}:{{ .Values.service.targetPort }}/api || exit 1"]
  restartPolicy: Never
  