apiVersion: v1
kind: Pod
metadata:
  name: "api-app-test-connection"
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["curl"]
      args: ["-v", "http://{{ .Values.Route.host }}/api"]
  restartPolicy: Never