apiVersion: v1
kind: Pod
metadata:
  name: "api-app-test-connection"
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: curl
      image: curlimages/curl
      command: ['curl', 'http://api-app-service:5000/api']
  restartPolicy: Never
